version: '3.8'
services:
  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - frontend_local:/app/result_build/
                       /app/build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - frontend_local:/usr/share/nginx/html/build

volumes:
  frontend_local:
