export const PATH = {
  HOME: '/',
  PROFILE: 'profile',
  USER: 'user',
  AUTH: '/auth',
  AUTH_MAIL: '/auth/mail',
  REGISTRATION: 'registration',
  PASSWORD_RESET: 'password/reset',
  PASSWORD_RESET_CONFIRM_D: 'password/reset/confirm/:id/:confirmCode',
  EMAIL_COMFIRM_D: 'email/confirm/:confirmCode',
  GOOGLE_CODE: 'google/code/',
  SUCCESS: 'success',
  RESEND_REGISTER: 'resend-register',
  RESEND_PASSWORD: 'resend-password',
};
