name: dev frontend githance workflow

on:
  push:
    branches:
      - feature/deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: githance_backend
  DEPLOY_PATH: GITHANCE_DEV
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: db_dev
  DB_PORT: 5432
  BACK_HOST: backend_dev

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        -
          name: Executing deploy via ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SRV_HOST }}
            username: ${{ secrets.SRV_USER }}
            key: ${{ secrets.SRV_SSH_KEY }}
            passphrase: ${{ secrets.SRV_SSH_PASSPHRASE }}
            script: |
              cd ${{ env.DEPLOY_PATH }}              
              echo "test is ok" > test.txt
